language: node_js
node_js:
- '0.10'
script:
- grunt coffeelint
notifications:
  hipchat:
    rooms:
      secure:
    template:
    - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: change
